/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef module_one_h
#define module_one_h

/* function declarations */
void init_module_one(void);

Netsnmp_Node_Handler handle_nstAgentPluginLogin;

void deinit_module_one(void);

#endif /* module_one_h */
