/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "module_one.h"

static char nstAgentPluginLogin_object[8] = "xabram00";
static oid nstAgentPluginLogin_oid[] = { 1,3,6,1,3,22,1 };

/** Initializes the module_one module */
void
init_nstAgentPluginLogin(void)
{
    
  DEBUGMSGTL(("module_one", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("nstAgentPluginLogin",
                                            handle_nstAgentPluginLogin,
                                            nstAgentPluginLogin_oid, 
                                            OID_LENGTH(nstAgentPluginLogin_oid),
                                            HANDLER_CAN_RONLY
        ));

}

int
handle_nstAgentPluginLogin(netsnmp_mib_handler *handler,
                           netsnmp_handler_registration *reginfo,
                           netsnmp_agent_request_info   *reqinfo,
                           netsnmp_request_info         *requests)
{
    switch(reqinfo->mode) {
        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb,
                                     ASN_OCTET_STR,
                                     (u_char*) &nstAgentPluginLogin_object,
                                     strlen(nstAgentPluginLogin_object));
            break;
        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_nstAgentPluginLogin\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}

void
deinit_nstAgentPluginLogin(void)
{
    unregister_mib(nstAgentPluginLogin_oid, OID_LENGTH(nstAgentPluginLogin_oid));
}