/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef XABRAM00_MIB_H
#define XABRAM00_MIB_H

/* function declarations */
void init_XABRAM00_MIB(void);
Netsnmp_Node_Handler handle_nstAgentPluginLoginObject;
Netsnmp_Node_Handler handle_nstAgentPluginTimeInRFC3339;
Netsnmp_Node_Handler handle_nstAgentPluginInt32Object;
Netsnmp_Node_Handler handle_nstAgentPluginReleaseVersion;

#endif /* XABRAM00_MIB_H */
